// <auto-generated />
using System;
using ApiExcelAutomation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiExcelAutomation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923150031_SeedEmployees")]
    partial class SeedEmployees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiExcelAutomation.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "IT",
                            Email = "rahul.sharma@example.com",
                            JoiningDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rahul Sharma",
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 2,
                            Department = "HR",
                            Email = "priya.das@example.com",
                            JoiningDate = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Priya Das",
                            Salary = 58000m
                        },
                        new
                        {
                            Id = 3,
                            Department = "Finance",
                            Email = "amit.kumar@example.com",
                            JoiningDate = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amit Kumar",
                            Salary = 72000m
                        },
                        new
                        {
                            Id = 4,
                            Department = "IT",
                            Email = "sneha.patel@example.com",
                            JoiningDate = new DateTime(2021, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sneha Patel",
                            Salary = 81000m
                        },
                        new
                        {
                            Id = 5,
                            Department = "Sales",
                            Email = "arjun.singh@example.com",
                            JoiningDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Arjun Singh",
                            Salary = 55000m
                        },
                        new
                        {
                            Id = 6,
                            Department = "Finance",
                            Email = "neha.roy@example.com",
                            JoiningDate = new DateTime(2023, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Neha Roy",
                            Salary = 69000m
                        },
                        new
                        {
                            Id = 7,
                            Department = "IT",
                            Email = "vikash.das@example.com",
                            JoiningDate = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vikash Das",
                            Salary = 92000m
                        },
                        new
                        {
                            Id = 8,
                            Department = "HR",
                            Email = "anjali.mishra@example.com",
                            JoiningDate = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Anjali Mishra",
                            Salary = 62000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
